app = "oncolife-patient-api"
primary_region = "sjc"

[build]
  dockerfile = "apps/patient-platform/patient-api/Dockerfile"

[env]
  PORT = "8000"
  PYTHONUNBUFFERED = "1"

[[services]]
  internal_port = 8000
  protocol = "tcp"

  [services.concurrency]
    type = "requests"
    soft = 200
    hard = 300

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "10s"
    restart_limit = 0 