app = "oncolife-patient-frontend"
primary_region = "sjc"

[build]
  dockerfile = "apps/patient-platform/patient-server/Dockerfile"
  [build.args]
    VITE_API_BASE = "/api"
    VITE_WS_BASE = "/api"

[env]
  NODE_ENV = "production"
  PORT = "3000"
  BACKEND_URL = "http://oncolife-patient-api-backend.internal:8000"
  API_BASE = "http://oncolife-patient-api-backend.internal:8000"

[[services]]
  internal_port = 3000
  protocol = "tcp"

  [services.concurrency]
    type = "requests"
    soft = 100
    hard = 150

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "10s"
    restart_limit = 0 